### ISSUE TITLE
Asynchronous meta-text extractor for blobs [infra]

### ISSUE THREAD

**Issue by akindyakov** [mazed-dev/truthsayer#119]
Asynchronous meta-text extractor for blobs to be able to search among them.

This is about infrastructure to do that. For actual extractors implementations better to create separate tasks

- [ ] For documents - text extraction
- [x] For images - some image recognition technique.
- [ ] For voice recordings - some voice recognition.

Part of Thread-knowledge/truthsayer#110
