### ISSUE TITLE
Offline mode

### ISSUE THREAD

**Issue by akindyakov** [mazed-dev/truthsayer#351]
Implementation plan: - ~50 hours total
- truthsayer -> archaeologist comms experiment - ~6 hours total
    - [x] Chrome: message-based comms - ~2 hours https://github.com/mazed-dev/truthsayer/pull/381
    - [ ] Firefox: event-based comms - ~4 hours
- [direction abandoned] ~~Add db to archaeologist - around 8 hours total~~
    - [x] ~~Plug in SQLite with a trivial proof that it works - around 4 hours https://github.com/mazed-dev/truthsayer/pull/387~~
    - [x] ~~Mirror smuggler's db table layout - around 4 hours~~
- Re-implement smuggler-api - ~20 hours total
    - [x] [direction abandoned] ~~for background, using SQL directly - around 16 hours~~
    - [x] for background, using `browser.storage.local` - around 16 hours - #396 
    - [x] for truthsayer, using truthsayer -> archaeologist - ~4 hours #401
- Amend truthsayer/archaeologist UI workflows if needed (e.g. hide "login" buttons etc) - ~16 hours 
    - [x] expose local hosting option with bare bones UX #404
