### ISSUE TITLE
🧄 Distribution of augmented suggestions [root]

### ISSUE THREAD

**Issue by akindyakov** [mazed-dev/truthsayer#450]
## Todo
- [x] Augment page with Mazed reading suggestions
- [ ] ~Hotkey to open list of suggestions~ → decided to postpone this as not most critical feature to onboard our first 10 active users.
- [x] Remove corner tag of writing augmentation
- [x] Draggable overlayed Mazed Icon, [source](https://mazed-dev.slack.com/archives/C02A1RF4AP3/p1676627373168079?thread_ts=1676626656.535759&cid=C02A1RF4AP3)
- [x] #443 -- #466
- [x] Make floater draggable only along vertical line. --

### Added 24 Feb
- [ ] ~Cover floater/suggestions with feature flag. To disable it quickly if we break something or annoys users too much with it.~ → released without it, because we don't have that many active users #movefast

## Added 26 Feb
- [x] Persist state of a floater between tags. For now only the openness parameter of a floater.
- [x] #505

## Added 27 Feb
- [x] Make sure suggestions are refreshed with every `document.URL` change

## Added 1 March
- [x] More compact layout for revealed list of suggestions (smaller margin on the top and right hand side)
- [x] Persist position of the floater within the same tab → #480 

## Added 2 March
- [x] 🪲 Bookmark is suggested to the original page.
- [x] 🪲 Augmented writing is not working for a switch between reading and writing on a same page.
