### ISSUE TITLE
Spring started on March 3d, 2023

### ISSUE THREAD

**Issue by akindyakov** [mazed-dev/truthsayer#484]
## 🔥 To-do

- [x] #503
- [x] Onboarding texts amends. Graham.
- [x] #480 
- [x] #483    →  #482 
- [x] Ironing out loading open tabs. ETA, end of this week.
- [x] Bug: don't suggest page for itself → #485 
- [x] #501
- [x] Sudden log offs problem. Make auth tokens not expire.
- [x] Link button in suggestions should lead to the original page. Enable editing functionality on a suggestions & pop cards. → #486 
- [x] Editable comment under the main bookmark in Archaeologist Pop Up window → #487 

## 🚫 Not-do

1. Change the domain to [mazed.dev](http://mazed.dev/).
2. No new design & UX for suggestions augmentation.
3. An improved preview little more preview.
4. GDoc improvements.
