### ISSUE TITLE
Posthog Metrics | Ability to view onboarding date of user

### ISSUE THREAD

**Issue by grieve17** [mazed-dev/truthsayer#556]
Today: in Posthog, it's difficult to track whether we're improving at all, because it appears we don't have the capability to see when individual users onboarded. 

Tomorrow: i'd like to be able to understand our users by the cohort in which they onboarded. Understanding that we're doing things that are improving retention will be possible only if we're tracking when we onboarded them, and measure user retention & engagement by cohort. 

If we're able to measure #of users that open the floater 5 times a week, we'll be able to understand user growth, retention, and engagement all in one metric.

```[tasklist]
### Tasks
- [x] Experiment with PostHog's user retention tooling - https://eu.posthog.com/insights/uvNYG9OA
- [x] Make cohorting & retention events reliable to track - https://github.com/mazed-dev/truthsayer/pull/692
- [x] Ensure ["User used one of the core Mazed features" action](https://eu.posthog.com/data-management/actions/6623) covers all crucial user flows -- feedback [here](https://mazed-dev.slack.com/archives/C02A1RF4AP3/p1682249671126869?thread_ts=1682192635.787689&cid=C02A1RF4AP3)
- [x] ~Switch to the "real" criteria for finished onboarding is that archaeologist was installed. To do that, `background` needs to be able to publish metrics - #691~
- [x] Update dashboards to use the reliable events
```
