### ISSUE TITLE
Send Investor Letter

### ISSUE THREAD

**Issue by grieve17** [mazed-dev/truthsayer#609]
```[tasklist]
### Tasks
- [ ] https://github.com/mazed-dev/truthsayer/issues/613
- [ ] https://github.com/mazed-dev/truthsayer/issues/612
- [ ] https://github.com/mazed-dev/truthsayer/issues/611
- [ ] https://github.com/mazed-dev/truthsayer/issues/627
```
