### ISSUE TITLE
Ship release notes

### ISSUE THREAD

**Issue by grieve17** [mazed-dev/truthsayer#614]
```[tasklist]
### Tasks
- [ ] https://github.com/mazed-dev/truthsayer/issues/618
- [ ] https://github.com/mazed-dev/truthsayer/issues/617
- [ ] https://github.com/mazed-dev/truthsayer/issues/616
- [ ] https://github.com/mazed-dev/truthsayer/issues/623
- [ ] https://github.com/mazed-dev/truthsayer/issues/628
- [x] add gif to email
```
