### ISSUE TITLE
Distill notes from customer interviews to MVP

### ISSUE THREAD

**Issue by grieve17** [mazed-dev/truthsayer#619]
```[tasklist]
### Tasks
- [x] Distill notes form Brian Lalli
- [x] Distill notes from Jacob
- [x] Distill Notes from Mel
- [x] Distill Notes from Spru
- [x] Distill notes from Gio
- [x] Sean
- [x] notes from eli
```
