### ISSUE TITLE
Onboarding Iteration

### ISSUE THREAD

**Issue by grieve17** [mazed-dev/truthsayer#620]
```[tasklist]
### Tasks
- [ ] https://github.com/mazed-dev/truthsayer/issues/622
- [ ] https://github.com/mazed-dev/truthsayer/issues/624
- [ ] https://github.com/mazed-dev/truthsayer/issues/621
- [ ] https://github.com/mazed-dev/truthsayer/issues/626
- [ ] https://github.com/mazed-dev/truthsayer/issues/630
```
