### ISSUE TITLE
Outreach Graham's network

### ISSUE THREAD

**Issue by grieve17** [mazed-dev/truthsayer#662]
```[tasklist]
### Tasks
- [ ] onboard users who do heavy research (now)
- [ ] onboard bizdev users who use linkedin/ gmail later in the week (bizdev, founders, VCs)
- [ ] keep list up to date
```
