### ISSUE TITLE
IP Strategy

### ISSUE THREAD

**Issue by grieve17** [mazed-dev/truthsayer#730]
```[tasklist]
### Tasks
- [ ] come up with list of trademarks (i.e. second brain) (foreword) , (Mazed)
- [ ] research each one, to see what's trademarkable
- [ ] determine total cost
- [ ] execute
```
