### ISSUE TITLE
M9 Floater overhaul

### ISSUE THREAD

**Issue by grieve17** [mazed-dev/truthsayer#743]
```[tasklist]
### Tasks
- [ ] Floater is shown over full screen video e.g. YouTube, Netflix
- [ ] Spinner on a minimised floater attracts attentions and thus distracts users.
- [ ] Floater doesn't persist it's position, often jumps back to default position.
- [ ] Minimised floater is too big on it's own and often obstructs access to a host page elements.
- [ ] Floater is shown on pages where user doesn't want to see suggestions at all.
- [ ] There is no way to hide floater when needed.
- [ ] Functional: User can't "pin" certain suggestions.
- [ ] Functional: User doesn't see quotes in a floater. (?)
- [ ] Functional: User can't add comments in a floater.
- [ ] Floater cards dont' have enough spacing, making all cards blend together rather than be individual items
- [ ] users can't delete certain suggestions
- [ ] clicking is cumbersome, & leaving floater open can be annoying as well. Constantly minimizing is a negative feedback loop
- [ ] when floater is open, cards showing up and deleting as I write is a little jerky and attention grabbing.

````[tasklist]
### Tasks
- [ ] Floater doesn't persist it's position, often jumps back to default position.
```[tasklist]
### Tasks
- [ ] Minimised floater is too big on it's own and often obstructs access to a host page elements.
```[tasklist]
### Tasks
- [ ] Floater is shown on pages where user doesn't want to see suggestions at 

- [ ] There is no way to hide floater when needed.
````
```
```
```
```
```
```
```
```
```
```
```
```
```


```

```

```
