### ISSUE TITLE
ensure metrics don't erroneously downplay the actual number of users

### ISSUE THREAD

**Issue by grieve17** [mazed-dev/truthsayer#753]
```[tasklist]
### Tasks
- [ ] https://github.com/mazed-dev/truthsayer/issues/768
- [ ] https://github.com/mazed-dev/truthsayer/issues/770
- [x] add an additional PostHog insight which measures users who didn't touch floater, but left it open (with investors as a target audience, to complement more ["hard evidence of usage" metrics](https://eu.posthog.com/data-management/actions/6623)) - https://github.com/mazed-dev/truthsayer/pull/773
```
