### ISSUE TITLE
allow for more users to report metrics (via a reverse proxy)

### ISSUE THREAD

**Issue by SergNikitin** [mazed-dev/truthsayer#768]
```[tasklist]
### Tasks
- [x] set up a reverse proxy
- [x] make truthsayer & archaeologist send data via proxy - #767
- [x] make sure proxy comes up reliably in the droplet
- [x] version control the proxy setup in https://github.com/mazed-dev/posthog-reverse-proxy - https://github.com/mazed-dev/posthog-reverse-proxy/pull/1
- [x] set up alarms to alert us if proxy goes down - [alert here](https://cloud.digitalocean.com/monitors/uptime/checks/6f4297e7-3c7e-4eb0-839c-1854e8972ac0?i=2ec704)
```
