### ISSUE TITLE
improve overall performance of critical user flows

### ISSUE THREAD

**Issue by akindyakov** [mazed-dev/truthsayer#782]
```[tasklist]
### Tasks
- [ ] https://github.com/mazed-dev/truthsayer/issues/797
- [ ] #822
- [x] ~~Improve search performance further, if #777 is not enough~~ -- yes, it is not enough
- [ ] https://github.com/mazed-dev/truthsayer/issues/792
- [x] ~~check if #826 helps~~ -- no, not right now
- [ ] https://github.com/mazed-dev/truthsayer/pull/827
- [ ] https://github.com/mazed-dev/truthsayer/issues/833
- [ ] improve search performance
```
