### ISSUE TITLE
Fix issues related to slow `background` startup

### ISSUE THREAD

**Issue by SergNikitin** [mazed-dev/truthsayer#792]
Slow startup creates user-facing issues such as
- errors in popups
- login popup is shown temporarily even though user is logged in
- failure to serve suggestions
- inability to save a page
- etc

```[tasklist]
### Tasks
- [x] Measure `background` performance - #791
- [x] Experiment with KNN tree creation performance -- see if [caching](https://github.com/tensorflow/tfjs/issues/633#issuecomment-576218643) it in `browser.storage.local` helps - https://github.com/mazed-dev/truthsayer/pull/800
- [x] See if more messages from content & popup (or maybe all of them) should have retry logic if background is in `loading` state -- no, the errors we have right now are not related to retries, they are caused by things like indeterministic init, no network connectivity etc
```
