### ISSUE TITLE
Rebrand to Foreword (root)

### ISSUE THREAD

**Issue by akindyakov** [mazed-dev/truthsayer#794]
```[tasklist]
### Tasks
- [ ] Publish a new landing page to `thinkforeword.com`.
- [ ] Publish legal docs under thinkforeword.com
- [ ] Reset password emails from mazed@fastmail.com → noreply@thinkforeword.com
- [ ] Release rebranded web app: change the names and all URL's.
- [ ] Release rebranded Chrome extension: change the names and all URL's.
- [ ] In-app release notes for users, #789.
- [ ] Redirect from mazed.se/<legal> to thinkforeword.com
- [ ] Rebrand letter to investors.
- [ ] Social Network update: Alex
- [ ] Email redirect from `mazed.dev` →  `thinkforeword.com`
- [ ] Redirect non-authorised users from WebApp to `thinkforeword.com`
- [ ] ~~Set up a new URL for the web app (and purchase it). Options: `foreword.run`, `foreword.works`, `foreword.show`, `foreword.blue`, `thinkforeword.app`.~~
- [ ] ~~Redirect from `mazed.se` to a new web app URL.~~ Let's keep thing on mazed.se for now.
```
