### ISSUE TITLE
Onboarding: Step 2 | Account Sign Up

### ISSUE THREAD

**Issue by grieve17** [mazed-dev/truthsayer#842]
Location: [mazed.se/signup](http://mazed.se/signup)

Utility:

```[tasklist]
### Tasks
- [ ] https://github.com/mazed-dev/truthsayer/issues/840
- [ ] upon clicking sign up, user is taken to [mazed.se/onboarding](http://mazed.se/onboarding) - https://github.com/mazed-dev/truthsayer/pull/853/
```

UI

```[tasklist]
### Tasks
- [ ] shorten text box for email and name, anchoring to the left side of the page
- [ ] Add new H1 text
- [ ] move TOS and PP sentence below email box
- [ ] change button to blue (2B7BFE)
- [ ] add "or sign into your account hyperlink, linking to https://mazed.se/login - https://github.com/mazed-dev/truthsayer/pull/853
- [ ] Change font to Noto Serif
- [ ] add social proof text and logos (lower priority)
- [ ] Add grey (F9FAFB) box containing social proof (lower priority)
```

<img width="677" alt="Screenshot 2023-06-29 at 5 13 41 PM" src="https://github.com/mazed-dev/truthsayer/assets/116609471/5a5a91b9-d67e-4c68-9316-2bfc5231c45d">
