### ISSUE TITLE
Onboarding Step 3: Welcome Page | mazed.se/onboarding

### ISSUE THREAD

**Issue by grieve17** [mazed-dev/truthsayer#843]
Location: mazed.se/onboarding

<img width="608" alt="Screenshot 2023-06-29 at 5 34 58 PM" src="https://github.com/mazed-dev/truthsayer/assets/116609471/b684264f-ee7b-40ac-8fbe-de20edab1a65">

location: [mazed.se/onboarding](http://mazed.se/onboarding)

Functionality:

```[tasklist]
### Tasks
- [ ] maintain hyperlink button to chrome store
```

UI:

```[tasklist]
### Tasks
- [ ] remove: "instant, automatic, private" and checkboxes
- [ ] add H1 and H3 texts
- [ ] change fonts and colors:
```
—font: Noto Serif
-Colors: 
——blue: 2B7BFE
—white: FFFFFF
