### ISSUE TITLE
Step 7: Sign up confirmation email

### ISSUE THREAD

**Issue by grieve17** [mazed-dev/truthsayer#847]
Location: Email sent from Digital ocean

Functionality:

```[tasklist]
### Tasks
- [x] ~~button links to /password-recovery-reset page~~ -- currently it's only cheap to do plain text :(
```
UI:

```[tasklist]
### Tasks
- [x] remove previous text
- [x] add subject: Please confirm your signup with Foreword
- [x] add email body text, including plain link in case hyperlink does not work
- [x] insert user's Name in greeting. If effort is greater, remove greeting.
```
Lower priority
```[tasklist]
### Tasks
- [x] ~~add blue button (2B7BFE), with white text~~ -- currently it's only cheap to do plain text :(
```

```

<img width="522" alt="Screenshot 2023-06-29 at 6 16 21 PM" src="https://github.com/mazed-dev/truthsayer/assets/116609471/5070d9da-4b07-46bf-8dd0-e06c9ea6b830">
