### ISSUE TITLE
Onboarding Step 8: Password reset page

### ISSUE THREAD

**Issue by grieve17** [mazed-dev/truthsayer#848]
Location: password reset page

Utility
```[tasklist]
### Tasks
- [ ] button links to [mazed.se/login](http://mazed.se/login)
```

```[tasklist]
### Tasks
- [ ] modify text to say "Create new password" in both locations
- [ ] make button blue (2B7BFE)
- [ ] left-anchor button below lefthand side of text box
```
