### ISSUE TITLE
Edits to navigation bar in onboarding flow: remove Mazed spool & search bar

### ISSUE THREAD

**Issue by grieve17** [mazed-dev/truthsayer#851]
```[tasklist]
### Tasks
- [ ] remove mazed spool from next to the _foreword_ logo on every step of the web app, both in the sign up flow and . Reason: it cheapens the brand, and looks unprofessional, leading to a greater likelihood of churn. 
- [ ] remove search bar from onboarding pages. This is a distraction that could lead users to begin searching for something and fall out of the onboarding flow. Locations below:

```

locations for search bar removal: 

```[tasklist]
### Tasks
- [ ] [mazed.se/signup](http://mazed.se/signup)
- [ ] [mazed.se/onboarding](http://mazed.se/onboarding)
- [ ] [https://mazed.se/onboarding?step=1](https://mazed.se/onboarding?step=1)
- [ ] [Mazed.se/login](http://mazed.se/login)
- [ ] password reset page
```
