### ISSUE TITLE
public launch - July 2023 [root]

### ISSUE THREAD

**Issue by SergNikitin** [mazed-dev/truthsayer#852]
```[tasklist]
### Tasks
- [ ] https://github.com/mazed-dev/truthsayer/issues/840
- [ ] https://github.com/mazed-dev/truthsayer/issues/842
- [ ] https://github.com/mazed-dev/truthsayer/issues/843
- [ ] https://github.com/mazed-dev/truthsayer/issues/844
- [ ] https://github.com/mazed-dev/truthsayer/issues/845
- [ ] https://github.com/mazed-dev/truthsayer/issues/846
- [ ] https://github.com/mazed-dev/truthsayer/issues/847
- [ ] https://github.com/mazed-dev/truthsayer/issues/848
- [ ] https://github.com/mazed-dev/truthsayer/issues/849
- [ ] https://github.com/mazed-dev/truthsayer/issues/850
- [ ] https://github.com/mazed-dev/truthsayer/issues/851
```
